name: shine
version: 0.1.0.0
github: "githubuser/shine"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2022 Author name here"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/shine#readme>

dependencies:
  - base >= 4.7 && < 5
  - relude
  - text
  - name: base
    mixin:
      - hiding (Prelude)
  - name: relude
    mixin:
      - (Relude as Prelude)

library:
  source-dirs: src
  dependencies:
    - boxes
    - colour
    - pandoc
    - pandoc-types
    - terminal-size
    - unordered-containers
    - word-wrap

executables:
  shine:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - shine
