name: shine
version: 0.1
github: "bandithedoge/shine"
license: GPL-3
author: bandithedoge
maintainer: "bandithedoge@protonmail.com"
copyright: "2022 Mikołaj Lercher"

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - relude
  - text
  - name: base
    mixin:
      - hiding (Prelude)
  - name: relude
    mixin:
      - (Relude as Prelude)

library:
  source-dirs: src
  dependencies:
    - hable
    - hashable
    - optstream
    - pandoc
    - pandoc-types
    - terminal-size
    - unordered-containers
    - word-wrap

executables:
  shine:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - shine
